Resolving openapi-gen 5.0 release error: APICLI-550 (#482)
* Resolving 5.0 release error: APICLI-550

Resolved the following exception:
  "Exception: 'null' defines discriminator 'type', but the referenced schema 'domain_record_a' is incorrect. invalid optional definition of type, include it in required"

Exception was happening for both domain_record and droplet_action. Basically whenever a discriminator is used to express polymorphism and a choice of object definitions, the objects definitions must have a type property set as required otherwise validation would fail.

after resolving issue, generator found a different error:

Exception: 'null' defines discriminator 'type', but the referenced schema 'floating_ip_action_unassign' is incorrect. invalid type for type, set it to string

will resolve in another jira ticket.

* resolving linting errors

some files required an example for "type"